"""
MaxLib - Next-generation asynchronous Python framework for MAX (max.ru / OneMe) messenger.
"""

__version__ = "3.1.0"
__author__ = "Onlysq"
__license__ = "GPL-3.0"

from .client import ClientPool, MaxClient
from .dispatcher import (
    BaseMiddleware,
    BaseStorage,
    Dispatcher,
    Filter,
    Handler,
    MemoryStorage,
    MiddlewareManager,
    State,
    StatesGroup,
    filters,
)
from .errors import (
    AuthBlocked,
    AuthBlockedError,
    AuthError,
    ChatNotFoundError,
    DownloadError,
    FloodWaitError,
    MaxError,
    MessageNotFoundError,
    NotConnected,
    NotConnectedError,
    PacketError,
    SessionExpired,
    SessionExpiredError,
    StopPropagation,
    TransportClosed,
    TransportClosedError,
    UploadError,
    UserNotFound,
    UserNotFoundError,
    VerifyCodeWrong,
    VerifyCodeWrongError,
)
from .protocol import Opcode, Transport, WebSocketTransport
from .session import BaseSession, JsonSession, MemorySession
from .types import (
    EMOJIS,
    Attachment,
    Audio,
    BaseObject,
    Chat,
    ChatMember,
    ChatType,
    Contact,
    Document,
    Event,
    Message,
    MessageDeletedEvent,
    MessageEditedEvent,
    MessageEvent,
    Name,
    Packet,
    Photo,
    Poll,
    PollOption,
    Presence,
    PresenceEvent,
    Reaction,
    ReactionCounter,
    ReactionEvent,
    ReactionInfo,
    Reactions,
    Sticker,
    TypingEvent,
    User,
    Video,
    Voice,
)
from .utils import (
    AsyncPagination,
    DeviceInfo,
    DownloadProgress,
    ProgressCallback,
    UploadProgress,
    download_file,
    format_text,
    parse_html,
    parse_markdown,
    upload_binary_data,
    upload_multipart_file,
)

# Legacy alias
Client = MaxClient

__all__ = [
    "MaxClient",
    "Client",
    "ClientPool",
    "filters",
    "Filter",
    "Dispatcher",
    "Handler",
    "BaseMiddleware",
    "MiddlewareManager",
    "State",
    "StatesGroup",
    "BaseStorage",
    "MemoryStorage",
    "Opcode",
    "Transport",
    "WebSocketTransport",
    "BaseSession",
    "JsonSession",
    "MemorySession",
    "Message",
    "Chat",
    "ChatMember",
    "ChatType",
    "User",
    "Contact",
    "Name",
    "Presence",
    "Attachment",
    "Photo",
    "Video",
    "Audio",
    "Voice",
    "Document",
    "Sticker",
    "Poll",
    "PollOption",
    "ReactionInfo",
    "ReactionCounter",
    "Reaction",
    "Reactions",
    "EMOJIS",
    "Packet",
    "BaseObject",
    "Event",
    "MessageEvent",
    "MessageEditedEvent",
    "MessageDeletedEvent",
    "ReactionEvent",
    "TypingEvent",
    "PresenceEvent",
    "MaxError",
    "NotConnectedError",
    "TransportClosedError",
    "PacketError",
    "AuthError",
    "VerifyCodeWrongError",
    "AuthBlockedError",
    "SessionExpiredError",
    "UserNotFoundError",
    "ChatNotFoundError",
    "MessageNotFoundError",
    "FloodWaitError",
    "UploadError",
    "DownloadError",
    "StopPropagation",
    "VerifyCodeWrong",
    "AuthBlocked",
    "UserNotFound",
    "NotConnected",
    "TransportClosed",
    "SessionExpired",
    "parse_markdown",
    "parse_html",
    "format_text",
    "upload_binary_data",
    "upload_multipart_file",
    "download_file",
    "UploadProgress",
    "DownloadProgress",
    "ProgressCallback",
    "DeviceInfo",
    "AsyncPagination",
]